---
- name: Download Scripts
  get_url:
    url: http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip
    dest: "{{ ansible_env.HOME }}"

- name: Unzip Files
  unarchive:
    src: "{{ ansible_env.HOME }}/CloudWatchMonitoringScripts-1.2.1.zip"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes
